services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER:guest
      - RABBITMQ_DEFAULT_PASS:guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - dbnet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - dbnet

  postgres-dev:
    image: postgres:17-alpine
    hostname: postgres-dev
    container_name: postgres-dev
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    networks:
      - dbnet
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17-alpine
    hostname: postgres-test
    container_name: postgres-test
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "db_app_generate_jokes_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_PORT: 5432
    networks:
      - dbnet
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data-dev:
  postgres-data-test:
  redis-data:
  rabbitmq-data:





